runtime: nodejs16

env_variables:
  NODE_ENV: production
  PORT: 8080

  TREASURY_ACCOUNT_ID: 0.0.3833523
  TREASURY_PRIVATE_KEY: 302e020100300506032b657004220420a9f9e81bbc4cc1d43af5fd4936713a2a9f2e2a66554987fe47e63d71ce7d3013
  TOPIC_ID_FORTUNE_WHEEL: 0.0.3851161
  RUN_TESTNET: true
  DB_USER: 'DB_USER'
  DB_PASSWORD_KEY: 'DB_PASSWORD_KEY'
  DATABASE: 'skiller_champion'
  DB_HOST: '127.0.0.1:5432'
  HEDERA_NODE_API: https://testnet.mirrornode.hedera.com

handlers:
  # Serve API routes using the Node.js app
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301

  # Serve static assets from the React build
  - url: /(.*\.(js|css|png|jpg|gif|ico|json|html|otf))$
    static_files: client/build/\1
    upload: client/build/.*\.(js|css|png|jpg|gif|ico|json|html|otf)$
    secure: always
    redirect_http_response_code: 301

  # Serve the index.html file for all other routes
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: client/build/index.html
    upload: client/build/index.html
