runtime: nodejs16

env_variables:
  NODE_ENV: st
  PORT: 8080

handlers:
  # Serve API routes using the Node.js app
  - url: /api/.*
    script: auto

  # Serve the React frontend's root index.html
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html

  # Serve any remaining requests with the React frontend's index.html
  - url: /.*
    static_files: client/build/index.html
    upload: client/build/index.html
