runtime: nodejs16

env_variables:
  NODE_ENV: st
  PORT: 8080

handlers:
  # Serve API routes using the Node.js app
  - url: /api/.*
    script: auto

  # Serve static assets from the React build folder
  - url: /(.*\.(js|css|png|jpg|gif|ico|json|html|otf))$
    static_files: client/build/\1
    upload: client/build/.*\.(js|css|png|jpg|gif|ico|json|html|otf)$

  # Serve the index.html file for all other routes
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: client/build/index.html
    upload: client/build/index.html
