runtime: nodejs16

env_variables:
  NODE_ENV: st
  PORT: 8080

handlers:
  # Serve all API requests to the Node.js app
  - url: /api/.*
    script: auto

  # Serve static assets from the React build folder
  - url: /(.*\.(js|css|png|jpg|gif|ico|json|html))$
    static_files: build/\1
    upload: client/build/.*\.(js|css|png|jpg|gif|ico|json|html)$

  # Serve the index.html file as the default page
  - url: /.*
    static_files: build/index.html
    upload: client/build/index.html
